Add 'connection lost' banner to the UI and display it whenever there is no connection to the server.
medienhaus/medienhaus-spaces pull request #47
Opened 2023-08-29 11:49 UTC by marcel-klasse

Displays a red banner whenever the connection to the matrix server is lost.

- [x] add state within `Matrix.js` to save the current connection state
- [x] display a UI element whenever the connection state is `false`

2023-08-30 12:23 UTC, fnwbr approved these changes

2023-08-30 12:23 UTC, fnwbr commented on components/UI/DisplayLostConncetion.js
> +import React from 'react';
File name: `Conncetion` or `Connection`?

2023-08-30 12:23 UTC, fnwbr commented on components/UI/DisplayLostConncetion.js
> +
@andirueckel Can you please review in terms of UI/UX?

![image](https://github.com/medienhaus/medienhaus-spaces/assets/706419/c7ee962a-ceb6-48c9-80bf-306876d925a0)

2023-08-30 12:26 UTC, fnwbr requested changes

2023-08-30 12:26 UTC, fnwbr commented on lib/Matrix.js
> +            // if we"ve lost connection to the server we set our state to false
`we"ve`?

2023-08-30 12:26 UTC, fnwbr commented on pages/_app.js
> +                    <DisplayLostConnection />
Also: `<DisplayLostConnection>` should just be called `<LostConnection>` in my opinion. React components are always about rendering, so it's kind of obvious that the component is responsible for **displaying** _some_ thing...

2023-08-30 12:28 UTC, fnwbr commented
I'll defer to @andirueckel for that, but the bottom right red thingy feels kind of out of line with our UI.
How about something bigger at the top, stretching across the whole page?

2023-08-30 12:38 UTC, andirueckel approved these changes

2023-08-31 09:41 UTC, fnwbr requested changes
One last thing, otherwise 👍

2023-08-31 09:41 UTC, fnwbr commented on components/UI/LostConnection.js
> +                { t('Waiting for server') }
Missing DE translation for this string

2023-09-02 09:21 UTC, fnwbr requested changes

2023-09-02 09:21 UTC, fnwbr commented on public/locales/de/_defaults.json
> +    "Connection Lost": "Verbindung unterbrochen"
`Connection Lost` vs `Connection lost` -- capital L vs lowercase L...
And while you're at it: Capital `S` in the line above for "Sekunden"

2023-09-02 09:24 UTC, fnwbr commented on components/UI/LostConnection.js
> +
NAB: Empty line

2023-09-05 13:29 UTC, andirueckel commented
> One last thing, otherwise 👍

Merging now. ✌️

2023-09-05 13:34 UTC, merged

2023-09-12 10:01 UTC, fnwbr commented
This is still missing the German translation for the `Connection lost` string 😕 
Seems like this happened in your very last merge w/ main @marcel-klasse...

2023-09-12 11:16 UTC, marcel-klasse commented
> This is still missing the German translation for the `Connection lost` string 😕 Seems like this happened in your very last merge w/ main @marcel-klasse...

fixed [bb4fa20](https://github.com/medienhaus/medienhaus-spaces/commit/bb4fa20e208436e4572c5a5e71baa5790e1b1597) ✌️